[package]
name = "testy"
version = "0.1.0"
authors = ["Shalom Yiblet <shalom.yiblet@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
tui = "0.6.2"
termion = "1.5"
subprocess = "0.1.18"
lazy_static = "1.4.0"
